services:
  neo4j:
    restart: unless-stopped
    environment:
      # neo4j-admin server memory-recommendation --memory=12G --docker
      NEO4J_server_memory_heap_initial__size: '4600m'
      NEO4J_server_memory_heap_max__size: '4600m'
      NEO4J_server_memory_pagecache_size: '4g'
      # It is also recommended turning out-of-memory errors into full crashes,
      # instead of allowing a partially crashed database to continue running:
      NEO4J_server_jvm_additional: "-XX:+ExitOnOutOfMemoryError"

  minio:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`storage.grapheos.cc`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  api:
    image: ghcr.io/oswatcher/graphql-api:latest
    pull_policy: always
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.grapheos.cc`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=4000"

  traefik:
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--log.level=INFO"

volumes:

# frontend is deployed on Github Pages
