version: '3.8'

services:
  api:
    build:
      context: ../graphql-api

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.filename=/certs.yml"
    volumes:
      - "./certs.yml:/certs.yml"
      - "./certs:/certs"

  frontend:
    depends_on:
      - api
    build:
      context: ../osw-frontend
    ports:
      - "8080:8080"
    environment:
      GRAPHEOS_API_URI: "https://api.localhost"
